### ISSUE TITLE
Diagnostic not triggering for .frag file

### ISSUE THREAD

**Issue by 0ctopirate** [racz16/WebGL-GLSL-Editor#17]
As above, everything is working in my .frag file, incl highlighting, formatting, and docs, but linting doesn't.

Perusing through the codebase, https://github.com/racz16/WebGL-GLSL-Editor/blob/4cca6ddc1eb74d14421f3b5a25ef29c09bb9bec7/src/extension.ts#L49-L74 looks to be the culprit.

My two theories are:
1. since it's a .frag extension file, the if statement fails and the code for linting never triggers. I'm not sure about this one since linting still doesn't work even after I change the extension to .glsl
2. the GlslDiagnosticProvider() constructor at the top is failing and getting caught, which doesn't do anything

This is a really sick library in every other way, I'd love to get this working.

**Comment by racz16** [comment]
First of all thanks for reporting the problem.
I don't think that your first theory is correct. These if statements check the language id and not the file extension. Also the '.frag' extension is registered in the package.json file. I just tried it with one of my own fragment shaders and it worked fine. 
Note that in '.glsl' files you don't get linting and it's not a bug. This is because '.vs' and '.vert' files determine that this is a vertex shader, '.fs' and '.frag' files determine that this is a fragment shader, '.glsl' files don't determine the shader stage. But I have to provide the shader stage to the compiler for linting. So I decided not to use linting in '.glsl' files. (Actually based on some keywords and functions only available in the vertex shader or in the fragment shader, I could predict the shader stage in some cases, but not in all cases.)
The snippet you show me runs when VS Code activates my extension (the first time you open a GLSL file). The mentioned try-catch is the last line of defense, because if I get some unexpected error here, it prevents the activation of other language features like code completion, formatting etc. But I think if you change a character or open another shader VS Code will trigger linting. So my best guess is that your code always cause some sort of unexpected error. This can be because it has some compile time error, or maybe you use regular GLSL and not GLSL ES. 
So please, provide an example shader to help me reproduce the problem. Is this only a problem in that specific shader or you don't get any errors even in the simplest fragment shader? What is your operating system? Have you installed other GLSL related extensions, for example linters?
