### ISSUE TITLE
Diagnotics doesn't work at MacOS

### ISSUE THREAD

**Issue by YohanBlessYou** [racz16/WebGL-GLSL-Editor#22]
I'm working on Windows10 and Mac(M1 Monterey). but only on Mac, diagnotics doesn't seem to work (all the other functions work well). all my friends have same problems. so I'm guessing it's not from my private things. I love this extension. I'm looking forward to solving this problem. is there something to know to let glslangValidatorMac work well? 

if I follow these steps, diagnotics works
1. `brew install glslang`
2. modify code like below

<img width="759" alt="image" src="https://user-images.githubusercontent.com/39155090/185621101-3115be74-837f-4326-bcbb-aa9208999e37.png">

**Comment by racz16** [comment]
Thank you for reporting the problem. Since I don't have any Mac devices, I can't really test the extension on Mac. I know that on Windows, glslangValidator works by default, on Linux I had to give permission to execute the file. Maybe there is something similar on Mac? In theory, the location of the extension's built-in compiler is `~/.vscode/extensions/raczzalan.webgl-glsl-editor-1.3.1/res/bin/glslangValidatorMac`. Could you please try to give permission to that file if it's possible? I'm not sure it's possible, maybe you have to enable it in System Preferences/Security & Privacy.
When I created the extension, the concept was that I include the compilers and the users don't have to install anything manually. So if it's possible to use the included compiler, I prefer that. If it's not, I will add an option to use an external compiler.

**Comment by tsherif** [comment]
Hi just wanted to note I had the same problem with this, and your hunch was correct. The executable seems to be installed with read/write permissions only.  But you don't have to go through Security and Privacy settings, just `chmod 744`.

Would it be possible to update the permissions as part of the installation ?
