### ISSUE TITLE
[Feature request] Option to break down function arguments to separate lines when formatting

### ISSUE THREAD

**Issue by heretique** [racz16/WebGL-GLSL-Editor#27]
Hi @racz16 

I've recently found your extension and I've started using it for my WebGL GLSL shader editing and I'm amazed how good it is.
I do have a feature request, if possible, it would be great if when formatting it can break the function parameter each into separate line if they're more than a small given number or if the function signature is longer than the line character limit (e.g. 120 chars) 
This:
```
vec4 getTerrainColor(
  in vec3 worldPos,
  in vec3 normal,
  in vec3 color,
  in sampler2D topDiffuseMap,
  in sampler2D sideDiffuseMap,
  in vec3 topDiffuse,
  in vec3 sideDiffuse,
  in float upwardsThreshold,
  in float topScale,
  in float sideScale)
{
    // make kinda upwards pointing normals to be upwards after a threshold
  float upwards = abs(normal.y);
  float upwardsThreshold = (1.0 - color.g) * upwardsThreshold;
  float upwardsStep = step(upwardsThreshold, upwards);
....
```
instead of this:
```
vec4 getTerrainColor(in vec3 worldPos, in vec3 normal, in vec3 color, in sampler2D topDiffuseMap, in sampler2D sideDiffuseMap, in vec3 topDiffuse, in vec3 sideDiffuse, in float upwardsThreshold, in float topScale, in float sideScale)
{
    // make kinda upwards pointing normals to be upwards after a threshold
  float upwards = abs(normal.y);
  float upwardsThreshold = (1.0 - color.g) * upwardsThreshold;
  float upwardsStep = step(upwardsThreshold, upwards);
...
```
Current formatting always does the latter.
If this is not a priority or there's not time for it, can you please provide some hints on how and where in the code could this be implemented.
Thank you.

**Comment by racz16** [comment]
Hello, thanks for the kind words. Your problem is totally valid, it sounds annoying. Unfortunately I think I won't have the time to implement it in the next couple of months, but eventually I will. So you can wait, or you can do it yourself. If you want to do it yourself, here's a little help. `GlslDocumentFormattingProvider` is the class which does the formatting. It's basically a state machine where I iterate through the tokens and based on the previous and the next token, I put a space, a new line or nothing between those 2 tokens. For example if the previous token was a `;` or a `}`, I put a new line between the previous token and the next token. However just those 2 tokens are sometimes not enough information. While we usually put a new line character after a `;`, it's not true if we're inside a `for` header. So I have to store additional information. In the `GlslVisitor` class's `visitFor_iteration` method, I store where the `for` headers are located in the code, and I take into account that information while I format the code. I already store where the function argument lists are, so using this information, you can implement the feature.

**Comment by heretique** [comment]
Thanks @racz16 for the explanation, I'll give it a try for an implementation in one of the following weekends when I have some spare time.

**Comment by racz16** [comment]
Hi, I implemented your request it'll be part of the next release. Here is the commit: 22c4638b8db5166e1bddc1feb44dee9bab651209. Feel free the give me feedback if my solution doesn't work well.

**Comment by heretique** [comment]
Wow, @racz16 thank you, I'll give it a try and let you know.

**Comment by crazyguysdev** [comment]
Hi, I was finding how to set line-limit and I found this issue.
But I couldn't find the limit number to set on setting.
Is there any option for setting the limit char number of each line?
