### ISSUE TITLE
Disable validator from config + validate working #includes?

### ISSUE THREAD

**Issue by dimateos** [racz16/WebGL-GLSL-Editor#30]
Hello, thanks for the great extension!

I was looking at past issues and wondering if there could be a simple option to toggle the **_validation_** instead of having to rename the shader to `.glsl`. Maybe a list of file extensions that the user wants to validate. On the same level, maybe there could also be an option to disable **_inline hints_** instead of relaying on disabling them globally for vscode.

And digging more into the validator, I was using some shader with `#include` directives and I could not get them to validate properly. I removed some errors by adding the extension [GL_GOOGLE_include_directive](https://www.reddit.com/r/opengl/comments/r2iqx4/what_even_is_gl_google_include_directive/) to the code injection (really nice feature btw). I still had `'#include' : Could not process include directive for header name: utils/structs.glsl` etc, so I tried to force the includes with `-l` in [executeValidation](https://github.com/racz16/WebGL-GLSL-Editor/blob/7098225f08c503a0e6ad067df7c3f2b36e2d53ec/src/providers/glsl-diagnostic-provider.ts#L143) (as suggested [here](https://github.com/KhronosGroup/glslang/issues/1691)). It seems to break the parsing? I put together a very simple test:

```glsl
//test-import.glsl
struct test {
    int a;
};
```
```glsl
//test.frag (no code injection to compare with validator)
precision highp float;

#extension GL_GOOGLE_include_directive : enable
#include "test-import.glsl"

void main() {
    test t;
    t.a = 1;
    vec3 v = vec2(2);
}
```

There are no warnings, but if I run the validator manually (I copied it in the cwd) I get the correct errors:
```bash
C:\...>glslangValidatorWindows.exe -C -l -S frag test.frag
test.frag
ERROR: test.frag:37: '=' :  cannot convert from ' const 2-component vector of float' to ' temp highp 3-component vector of float'
ERROR: 1 compilation errors.  No code generated.
```

My guess is that when using `-l` the errors show `filename:line:` even when there was no extra import. In contrast without `-l` goes `0:line` ([yep](https://github.com/racz16/WebGL-GLSL-Editor/blob/7098225f08c503a0e6ad067df7c3f2b36e2d53ec/src/providers/glsl-diagnostic-provider.ts#L188)):

```bash
test.frag
ERROR: 0:32: '#include' : Could not process include directive for header name: test-import.glsl
ERROR: 0:35: 'test' : undeclared identifier
ERROR: 0:35: '' :  syntax error, unexpected IDENTIFIER, expecting COMMA or SEMICOLON
ERROR: 3 compilation errors.  No code generated.
```

> I was gonna suggest upgrading to [shaderc](https://github.com/google/shaderc) but the validator seems to be almost the same, same output and basically the same usage too.

Well if at some point I got time in January I might make a PR, for now I will just disable the validator for myself. One question tho, does any other feature depend on the parsing of the validation? Cause errors in imported files might break stuff and I was thinking on just ignoring them for the current file.

cheers!

**Comment by racz16** [comment]
Hello, and thank you for your contribution!

Yes, it's a good idea to create an option to disable the validation. I'm sure there are a lot of cases when people put incomplete shader code into files and then put them together in runtime. I'm not so sure about disabling based on the file extension. What's the benefit of disabling the validation of vertex shaders while still validating fragment shaders?

About the inlay hints: there are multiple ways to influence the behavior of inlay hints, and I don't really want to add more options (in fact, there was an option to disable it until version 1.3.3, but I removed it because if felt that it was redundant). First of all, you can either enable or disable inlay hints globally. But actually, there are two more options: only show inlay hints if you press `ctrl`+`alt` and only hide it if you press `ctrl`+`alt`. And, of course, you can do either of them only in your workspace (not globally). Also, other extensions usually don't give you the option to disable individual features like code completion or inlay hints.

The include directive is an interesting one. As far as I understand, it only exists if you use Google's shaderc. My extension only supports WebGL GLSL shaders and not the desktop OpenGL or Vulkan GLSL shaders. In the end, these shaders will be compiled by the shader compiler provided by the browser, and the extension, you mention is not in the [WebGL extension list](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Using_Extensions#extension_list). Just to be sure, I tried it in Chrome and Firefox, but it doesn't work.
![image](https://user-images.githubusercontent.com/19560859/205451290-9746ede5-d74c-4088-ae3b-f16e45a48e28.png)
So if you use my extension to handle WebGL GLSL shaders, it's not a good idea to support include, because the browsers don't support it. If you use it with desktop OpenGL GLSL shaders, there are a ton of features that won't work, like implicit conversions, additional shader stages, and so on.

The validation doesn't influence any other features. I use the glslangValidator for the validation and display the results as errors and warnings. Other features use my own code parsing the source code. That's why the validator may accept any kind of valid GLSL code because glslangValidator knows all possible versions of GLSL. However, my code only knows WebGL GLSL shaders (GLSL ES 100 and GLSL ES 300). So, in theory, changing or disabling the validation won't affect other features.

**Comment by dimateos** [comment]
Hello! thanks for your answer

> About the inlay hints: there are multiple ways to influence the behavior of inlay hints, and I don't really want to add more options (in fact, there was an option to disable it until version 1.3.3, but I removed it because if felt that it was redundant). First of all, you can either enable or disable inlay hints globally. But actually, there are two more options: only show inlay hints if you press ctrl+alt and only hide it if you press ctrl+alt. And, of course, you can do either of them only in your workspace (not globally). Also, other extensions usually don't give you the option to disable individual features like code completion or inlay hints.

Well I am always a fan of more options when there is a good default configuration stablished! But I get your point and ofc not all extensions want to add options for everything. It was a mere suggestion as it does not seem too complex, I would not put it on any priority list ;) In my case I like inlay hints for c++/js (which include a wide range of configuration over the inlay hints options), but only for shaders in some occasions, so if I disable globally I lose them for the other part of the project.

> The include directive is an interesting one. As far as I understand, it only exists if you use Google's shaderc. My extension only supports WebGL GLSL shaders and not the desktop OpenGL or Vulkan GLSL shaders. In the end, these shaders will be compiled by the shader compiler provided by the browser, and the extension, you mention is not in the [WebGL extension list](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Using_Extensions#extension_list). Just to be sure, I tried it in Chrome and Firefox, but it doesn't work.

> So if you use my extension to handle WebGL GLSL shaders, it's not a good idea to support include, because the browsers don't support it. If you use it with desktop OpenGL GLSL shaders, there are a ton of features that won't work, like implicit conversions, additional shader stages, and so on.

It is also suported by glslang basically due to google pressure on khronos boards, but yep is not in the web standard. I indeed use the extension for desktop shaders, I feel like is the best one available even with the unsuported features... sorry bout that :)

> Yes, it's a good idea to create an option to disable the validation. I'm sure there are a lot of cases when people put incomplete shader code into files and then put them together in runtime. I'm not so sure about disabling based on the file extension. What's the benefit of disabling the validation of vertex shaders while still validating fragment shaders?

Yeah, from that POV you are definitely right. I was just thinking of skipping having to tell the stage to the validator (the `-S frag`) and just sending any file that the user wants to be validated: having a list of file extensions to check a match (initialized with just .vertex and .frag for example). The validator automatically detects the stage based on the file extension as noted in [glslang the repo readme ](https://github.com/KhronosGroup/glslang#execution-of-standalone-wrapper):

```md
The applied stage-specific rules are based on the file extension:
* .vert for a vertex shader
* .tesc for a tessellation control shader
* .tese for a tessellation evaluation shader
* .geom for a geometry shader
* .frag for a fragment shader
* .comp for a compute shader
```

But yep, this links with me using the extension for more than just web, this way the user could enable/disable the validator for any kind of shader! As you said, this feature does not influence the others so we could enhance it this way. I understand if this adds unwanted complexity, so yep again, at least a toggle to switch off would also work for me for now.

cheers!

**Comment by racz16** [comment]
Hello! I'm not sure I understand the last part of what you wrote. Do you mean that I should create 2 lists in the settings, where users can add file extensions? The extensions in the first list are treated like vertex shaders, and the extensions in the second list are treated like fragment shaders?

**Comment by racz16** [comment]
Hi, I added a new configuration, so now you can turn off the diagnostics. Here is the commit: 2707b370f240e3adc0efad154009b84f16e8006e. Feel free the give me feedback if my solution doesn't work well.

**Comment by dimateos** [comment]
Hello!

Sorry for the late response, I though I answered to your message back in december :(

> Hello! I'm not sure I understand the last part of what you wrote. Do you mean that I should create 2 lists in the settings, where users can add file extensions? The extensions in the first list are treated like vertex shaders, and the extensions in the second list are treated like fragment shaders?

I meant a single list of file extensions to apply the `glslangValidator` on. Then the validator alone has the feature to detect the stage based on the file extension (from their readme):

```md
The applied stage-specific rules are based on the file extension:
* .vert for a vertex shader
* .tesc for a tessellation control shader
* .tese for a tessellation evaluation shader
* .geom for a geometry shader
* .frag for a fragment shader
* .comp for a compute shader
```

> Hi, I added a new configuration, so now you can turn off the diagnostics. Here is the commit: 2707b37. Feel free the give me feedback if my solution doesn't work well.

I checked it out and checked the code and seems like a really good solution. I would forget the extension list thingy and keep it as it is.

Thanks a lot for the continued development!
