### ISSUE TITLE
Disable inlay hints?

### ISSUE THREAD

**Issue by McNull** [racz16/WebGL-GLSL-Editor#35]
Is there an option to disable the inlay hints? They drive me nuts.

**Comment by McNull** [comment]
Quick hack if anyone else is bothered by it.

https://gist.github.com/McNull/819e38dea0776ca3c135983d21535dc8

**Comment by racz16** [comment]
Hi, sorry for the late answer. About the inlay hints: there are multiple ways to influence the behavior of inlay hints, and I don't really want to add more options (in fact, there was an option to disable it until version 1.3.3, but I removed it because if felt that it was redundant). First of all, you can either enable or disable inlay hints globally. But actually, there are two more options: only show inlay hints if you press `ctrl`+`alt` and only hide it if you press `ctrl`+`alt`. And, of course, you can do either of them only in your workspace (not globally). Also, other extensions usually don't give you the option to disable individual features like code completion or inlay hints.

**Comment by surdu** [comment]
But why are inlay hints shown only by this extension if they are a global option?
