### ISSUE TITLE
#define breaks formatting (in some cases)

### ISSUE THREAD

**Issue by IiroUllin** [racz16/WebGL-GLSL-Editor#39]
e.g.

#define FUN float fun(){return 123.4;}
FUN

...after this the formatting will be broken

**Comment by racz16** [comment]
Yes, my extension, [can't handle preprocessor directives](https://github.com/racz16/WebGL-GLSL-Editor#known-issues). What it does is skip all lines starting with a `#`. It doesn't only break the formatter, it breaks almost all language features. From the formatter's point of view (which is just a state machine), the token `FUN` is just an identifier. Without preprocessing and macro expansion, it just looks like a variable name. So the formatter tries to format the code according to this.
There are workarounds though, for example instead of this:
```
#define FUN float fun(){return 123.4;}
FUN
```
write this:
```
#define FUN float fun(){return 123.4;}
FUN
#define MACRO \
;
```
This will help because again, my extension can't handle any preprocessing. It'll skip the lines starting with `#`, so it can only see `FUN` and `;`. Yes, it's pretty ugly but it can trick the formatter and make it work.
The real solution to this problem would be to write my own preprocessor, do a preprocessing stage and build a virtual document and do the analysis on this virtual document instead of the original document. To make this work, I would have to rewrite half of the extension.
However, there is good news: I plan to create a new extension that supports everything that this one does and more:
- supporting all GLSL versions and extensions,
- using the Language Server Protocol to better support embedded code, and to make it available as a Visual Studio extension as well,
- proper preprocessor support including the line continuation character, macro expansion, `#ifdef`s, and `#include`.

This is in a proof of concept stage and I'm not sure I can do everything I'd like to, especially make my language server work in Visual Studio.
So, in the long run, you'll hopefully have a GLSL extension that can properly handle preprocessing and much more, but until then, I'm afraid you have to deal with the workarounds.

**Comment by IiroUllin** [comment]
Thank you for the explanations and for all the work that you do on this project. Your formatter's pluses by far outweigh all these little issues. I like it so much, I don't mind adjusting my code a bit to make it happy :) Looking forward to more great things to come!
