### ISSUE TITLE
Ignore line feature

### ISSUE THREAD

**Issue by brandon-lb** [racz16/WebGL-GLSL-Editor#49]
Just wanted to say first that this is an AMAZING extension.

I really like the features, built-in documentation and how I was able to inject `es 300` to get rid of this problem: https://github.com/mrdoob/three.js/pull/26101#issuecomment-1703000037

I was wondering if there's a way to ignore a specific line though?

In three.js for example, you can have custom defines that are dynamically inserted in runtime. I obviously don't expect those to be reflected for this extension, but being able to ignore defines that don't seem to be present would be a great feature.
Something like
![image](https://github.com/racz16/WebGL-GLSL-Editor/assets/75831968/9feb16e4-0747-493c-9bb5-582620fa597f)

**Comment by racz16** [comment]
Thanks, I'm glad you like it. However, I don't fully understand what you mean by line ignoration. If you want my extension to ignore the line `#if ITERATION > 1`, it would create a compilation error because there is an `#endif` after it. If you want to ignore a macro definition, you can use something like this: `#undef ITERATION`. Sorry, maybe I'm completely off, if this doesn't help you, please try to explain it again.
