### ISSUE TITLE
Compatibility with Shader Toy extension

### ISSUE THREAD

**Issue by letmaik** [racz16/WebGL-GLSL-Editor#5]
First of all, great extension! I'm really impressed by the completeness and efficiency.

I'm trying to use this extension together with the https://github.com/stevensona/shader-toy extension. The issue is that the shader toy extension, like the Shadertoy website, auto-injects uniforms and the `#version` directive. In addition, the extension allows custom directives like `#iChannel0 "self"` to further configure the inputs. All of this means that I cannot use your extension together with the other extension, which is a real shame.

I'm not sure what the best solution here is, but how about the following: If any shadertoy uniform is used but wasn't defined, then the mode is automatically set to "shadertoy" and those uniforms and the version directive get auto-injected before running all the diagnostics etc. In addition, any unknown directives should be removed to avoid compile errors.

**Comment by racz16** [comment]
Yeah, I'm afraid, at the moment, you can't solve the problem. My extension can generate the ShaderToy variables to the code, however I guess, it would cause problems with the ShaderToy extension (like duplicated variables). The one thing you can do is to rename your files to '.glsl' extension. In this case my extension won't report any syntax errors, but you can use most of the other functions.
Sadly, now I don't have the time to implement anything because I'm writing my thesis. The solution what you suggest might work, but it could be complicated to inject and remove code. Then I would have to offset all my intervals (like where a certain function starts and ends in the code). 
At next year, I would like to spend some time in this project to implement a proper formatting and I'll try do something with this ShaderToy problem.
