### ISSUE TITLE
'round' : no matching overloaded function found 

### ISSUE THREAD

**Issue by YuFengjie97** [racz16/WebGL-GLSL-Editor#55]
### Content

![image](https://github.com/racz16/WebGL-GLSL-Editor/assets/34262325/9294c6f1-82da-43c4-88ea-0fa42db0c5d8)

round funciton can't match,but it can works

**Comment by YuFengjie97** [comment]
oh, i need write `#version 330 core` in the first of fs file

**Comment by YuFengjie97** [comment]
> oh, i need write `#version 330 core` in the first of fs file

But the definition version of this display will report an error in three.js. I guess the next step is that I should go to three.js to mention issue.

**Comment by racz16** [comment]
Hi! In short: you get an error because there is no `round` function in GLSL ES 100. If you add a version declaration `#version 330 core`, it would work on the desktop, but not in the browser, because WebGL only supports GLSL ES 100, and GLSL ES 300. If you use a version declaration `#version 300 es`, `round` should work just fine with Three.js.

A bit more explanation: OpenGL and GLSL versioning is a complete mess, so it's not obvious how it works. GLSL has 17 versions in total, and 13 of them work on the desktop, while 4 of them are used with OpenGL ES (basically the mobile version). GLSL ES versions are 100, 300, 310, and 320. However, only versions 100, and 300 are WebGL-compatible. So if you want to run it in the browser with Three.js, you have to use GLSL ES 100, or GLSL ES 300. If you use version declaration `#version 100`, the compiler will treat it as a GLSL ES 100 shader, and if you use `#version 300 es`, it'll treat it as a GLSL ES 300 shader. If you omit the version declaration, it'll default to GLSL ES 100. You can find useful tables in Wikipedia with all the GLSL shader language versions, the corresponding OpenGL versions, and the version declarations: https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versions. I also recommend you to use https://docs.gl, because it can tell you for example which shader language versions support [round](https://docs.gl/el3/round).
