### ISSUE TITLE
[Feature]:  Enable other features such as 'offline documentation' and so on,  in glsl strings after  /*glsl*/ comment.

### ISSUE THREAD

**Issue by rocketlyz** [racz16/WebGL-GLSL-Editor#56]
### Feature details

Glsl strings example as below:
```glsl
export const demoVS = /*glsl*/`#version 300 es
  in vec2 a_position;
  out vec4 color;

  void main() {
    vec4 = vec4(1, 0, 0, 0); 
  }
`
```
Expect to implement this functionality in glsl string as well as glsl files.

<img width="742" alt="image" src="https://github.com/racz16/WebGL-GLSL-Editor/assets/7335210/9d605b3e-431e-4fda-a2f5-9f6ddbf71d54">

**Comment by racz16** [comment]
Hi! My extension is a native VS Code extension, and only those extensions can support embedded languages that are based on the Language Server Protocol. So I would need to rewrite a big part of my extension to support this feature. And even Microsoft's official extensions don't fully support language features in embedded languages. So you get a better experience if you create a CSS than if you create a `<style>` tag in an HTML file. So I can't really implement this feature.
However, there are good news. I started to work on a new, Language Server Protocol-based extension. It is in a very early stage, you can't try it, and I couldn't work on it in the last couple of months, because I'm too busy working on other things. But I want to continue it at some point. It'll support all GLSL versions, preprocessor directives like `#include` statements, it'll work with Visual Studio as well, and a lot of other things. Supporting GLSL as an embedded language is definitely part of this, but I can't tell when will I have time for that project.
In the meantime, my advice is to use a bundler like Webpack to have your shaders in separate files, and during the bundling process, merge it into your final JavaScript file. This way, you can get full language support, while, you don't have to create HTTP requests for your shaders, and you might be able to even reduce the size of the source code.

**Comment by rocketlyz** [comment]
Thanks for your reply.
