### ISSUE TITLE
Symbols display is breaking in some cases causing disabling other useful features

### ISSUE THREAD

**Issue by theetcher** [racz16/WebGL-GLSL-Editor#6]
Hello!
I've discovered that some type defines breaks symbols outlines and most of useful features like hover hints, go to definitions and so on.

This is not working:
![image](https://user-images.githubusercontent.com/1951181/97818824-10aeba00-1ca5-11eb-8420-ec7bc3286696.png)

But this is ok:
![image](https://user-images.githubusercontent.com/1951181/97818841-2f14b580-1ca5-11eb-9ad0-97ec035d70c9.png)

PS. Your extension is awesome!

**Comment by theetcher** [comment]
Another case without define

this is not working
![image](https://user-images.githubusercontent.com/1951181/97819496-2faf4b00-1ca9-11eb-827b-208c03ebe9e8.png)

but this is ok
![image](https://user-images.githubusercontent.com/1951181/97819509-3b027680-1ca9-11eb-8dd5-1b966fbecb4d.png)

**Comment by racz16** [comment]
First of all, sorry for the late answer, I'm pretty busy now. The preprocessor directives are tricky, because they can appear almost anywhere and they can change the code dramatically. Currently I don't have solution for the problem, but I will work on it, because it causes problems in other places. The second problem is a bit simpler. First of all, you didn't declare the GLSL version, you want to use, so I have to interpret it as you want to use GLSL version 1.00. This is a problem, because mat4x3 is not part of the GLSL version 1.00. The another problem is that if you index a mat4x3 type variable, you get a vec3 and not a vec4. You may want to use a mat3x4 or return a vec3.
I plan to work on this project after I finish my thesis. Most likely after January.

**Comment by racz16** [comment]
I fixed the bug in [this commit](https://github.com/racz16/WebGL-GLSL-Editor/commit/fc56ec67db133021ca7ce346bcfd5f608d2d7886) and it'll be part of the next release. I plan to create a new release on late February or early March. However I didn't do anything in general with preprocessor directives so most likely there are some other similar bugs. I have an idea how to deal with the preprocessor directives, and I'll try to implement it on the next couple of days or weeks. I hope it'll work as I expect.
