### ISSUE TITLE
Use of extension within html script?

### ISSUE THREAD

**Issue by DanielWidmayer** [racz16/WebGL-GLSL-Editor#8]
Is there a possibility to use the Extension for html files that include glsl scripts?

In example I have a script with the type: `type="x-shader/x-fragment"` and another script with the type `type="x-shader/x-vertex"` and I would love to use your extension within these files too.

**Comment by racz16** [comment]
You can't use it that way. I'm pretty busy now because of my final exam, but yesterday I experimented a little bit. 
First of all,  most likely I can't enable the programmatic language features (like code completion, errors, go to definition etc.) in embedded code. Even the official embedded JavaScript and CSS extensions have limited capabilities in comparison to their normal versions. If I'm correct, only language server based extensions can enable embedded language features and my extension isn't based on language server. Another problem is that I can't just inject my language into HTML. The HTML extension have to explicitly list the possible embedded languages. It lists JavaScript, CSS and some others, but of course it doesn't list GLSL.
The syntax highlight is a little different, because I can inject my grammar into the HTML without the HTML extension's permission and I don't have to use language server. However it's still not easy. If I match a regex to the <script> tag to ensure to only use syntax highlight "x-shader/x-fragment" and "x-shader/x-vertex" type code, I have to color these lines too. If I don't, they remain uncolored which is definitely not something I want.
![type1](https://user-images.githubusercontent.com/19560859/103633682-5c503f00-4f46-11eb-8752-28063591e97f.png)
The second possible solution is to use GLSL syntax highlight on every line of unknown embedded code in HTML. So basically every line of code inside <script> tag except JavaScript. If you embed something other than GLSL and JavaScript, like an OBJ model, or anything else, it'll use GLSL syntax highlight on it.
![type2](https://user-images.githubusercontent.com/19560859/103634183-04660800-4f47-11eb-8a7e-4d777b1f5947.png)
On February I'll experiment more, because maybe there is a way to check the <script> tag's type without coloring it, but now my best guess is to add an option (which is disabled by default) to color all non JavaScript embedded code as GLSL.

**Comment by racz16** [comment]
I was able to implement the GLSL syntax highlight into the "x-shader/x-vertex" or "x-shader/x-fragment" type scripts in HTML in [this commit](https://github.com/racz16/WebGL-GLSL-Editor/commit/7f30e08f49d112e30c4e778e9ae4b6a91cd48c72) and it'll be part of the next release. I plan to create a new release on late February or early March. However I can't enable programmatic features in embedded GLSL code.
